### ISSUE TITLE
Infinite loop when linting Vue file containing TypeScript keyword

### ISSUE THREAD

**Issue by MatthiasKunnen** [vuejs/vue-eslint-parser#136] opened 2021-11-03 14:28 UTC
The @typescript-eslint/parser is stuck in an infinite loop when it encounters the words `static class` in the attributes of an element in a template of another file. Yes, this bug is weird.

**Reproduction**  
<https://github.com/MatthiasKunnen/eslint-vue-ts-keyword>

Examples of failing code:
```vue
<template>
    <div style="display: none"
         static
         class=""
    >
    </div>
</template>
```

```vue
<template>
  <div data-test="
        static
        class">
  </div>
</template>
```

**Result**  
Eslint crashes with `FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory`.
[Error log](https://github.com/vuejs/vue-eslint-parser/files/7468122/error.log)

Please check the reproduction repo for a more in-depth explanation and examples.

If I had to guess, the problem is that typescript-estree:createWatchProgram parses all files that are mentioned in the tsconfig's include property which makes it attempt to parse the <template> tags which causes the infinite loop. This despite the parser being set to `<template>: espree` in the ESLint config. Now the question is if this can be avoided.

**Comment by ota-meshi** [comment] 2021-11-04 07:46
Thank you for posting this issue.
I have debugged in your repository and it looks like typescript is hanging trying to parse the contents of `hang-cause.vue `as `.ts`.

I probably can't solve this problem.
Can you open the problem in the typescript-eslint repository as well?

Also trying to lint by renaming `hang-cause.vue` to` hang-cause.ts` using `@typescript-eslint/parser` without `vue-eslint-parser` can also hang processing.

**Comment by ota-meshi** [comment] 2021-11-04 08:00
It seems that it can also be hung by processing a ts file with the following content:

```ts
""
static
class
```

**Comment by ota-meshi** [comment] 2021-11-04 08:05
Hmm. This may be a typescript bug. If you have this file, tsc will not finish processing.

**Comment by MatthiasKunnen** [comment] 2021-11-04 10:05
I'm not familiar with the inner workings of ESLint but I assume it is not possible to only feed the code in `<script lang="ts">` tags to `@typescript/eslint-parser` and have it not parse the whole file?

**Comment by ota-meshi** [comment] 2021-11-04 10:18
I'm not familiar with the internal processing of ts-eslint, so I'm not sure.

**Comment by ota-meshi** [comment] 2021-11-05 06:43
If you want this issue resolved, open the issue in the TypeScript repository.
I think the following code should be used for the reproduction code described in the TypsScript issue.

```ts
""
static
class
```

I close this issue because there is nothing I can do with this repository.

**Closed by ota-meshi** 2021-11-05 06:43 UTC
Labels: bug, help wanted
